[FIX] sale_commission_product_criteria: Get items without commission
Otherwise the following error happens:
ERROR: operator does not exist: integer = boolean
LINE 9:             AND (item.commission_id = false)
                                            ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts