[BKP] sale_commission: Add missing company_id and currency_id fields after backporting from 11.0 Otherwise get this: commission/sale_commission/models/settlement.py", line 198, in _check_company     if record.agent_line.company_id != record.company_id: AttributeError: 'account.invoice.line.agent' object has no attribute 'company_id'